### ISSUE TITLE
Is it possible to pass field data through to the webhook url?

### ISSUE THREAD

**Issue by duncanmunro** [moritzebeling/kirby-panel-button#1]
Pushing the boundaries of my experience here so apologies if this is a trivial question. I have the refresh button working fine – its url (which is to within the kirby site) gets captured by a kirby hook and returns whatever arbitrary data i set it to. What I really want though is to act on current, unsaved, values in the panel page. Is this possible? Thanks.

**Comment by moritzebeling** [comment]
Hey, do I understand correctly, that you want to send your current, unsaved data to some Kirby route, process it and receive it back in the panel?

(In any case, I am not sure if this plugin is of help for your purpose as it is not meant for transporting or processing data, but only for triggering some endpoint or webhook.)

**Comment by duncanmunro** [comment]
OK. Gotcha. All good, thanks.
